### ISSUE TITLE
Getting startup error

### ISSUE THREAD

**Issue by thiagolocatelli** [jbasdf/react-kindling#7]
just cloned the repository and ran "npm install". When I try "npm start" or "gulp, I get the following error:

[thiago@golias ~/dev/node/react-kindling (master)] npm start

> react_kindling@0.0.1 start /Users/thiago/dev/node/react-kindling
> gulp

module.js:338
    throw err;
    ^
Error: Cannot find module './secrets.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/thiago/dev/node/react-kindling/config/settings.js:3:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! react_kindling@0.0.1 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react_kindling@0.0.1 start script 'gulp'.
npm ERR! This is most likely a problem with the react_kindling package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls react_kindling
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/thiago/dev/node/react-kindling/npm-debug.log

**Comment by thiagolocatelli** [comment]
My bad, figure it out.
